### ISSUE TITLE
react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. 

### ISSUE THREAD

**Issue by Pramod-Butte** [stephenwf/use-open-seadragon#25]
Hi I like the idea of using openseadragon as a custom hook, but I am getting following error at

my code:

DziImageViewerHook.js

`import React from "react";
import { useOpenSeadragon } from "use-open-seadragon";

function DziImageViewerHook(props) {
  const tile = {
    type: "image",
    url:
      "https://openseadragon.github.io/example-images/grand-canyon-landscape-overlooking.jpg"
  };

  const [ref] = useOpenSeadragon(tile);

  return (
    <div ref={ref} style={{ height: 600, width: 800, position: "relative" }} />
  );
}
export default DziImageViewerHook `

and then on the App.js

`import  DziImageViewerHook from  'DziImageViewerHook'
//......

return(
<>
<DziImageViewerHook />
</>
)
`

Any suggestions as to what ma i doing wrong?

**Comment by stephenwf** [comment]
I'm not sure, based on the code provided. Would it be possible to replicate on Codesandbox? Here is a sandbox you can fork: https://codesandbox.io/s/use-open-seadragon-overlay-wi8lb

**Comment by Pramod-Butte** [comment]
Thank you the response.

So far I think it may be mismatched version of react ...
I am on 17.0.2 and I think the version being used in 16.10.2, although that in itself should not be a problem.

I will try to replicate in codesandbox.

**Comment by Pramod-Butte** [comment]
Ok I got it. If anyone has a same problem the solution is to override the devdependancy.

just add an override in package.json to force the package to use the applications version of react instead of the library version.

package.json:

```
},
  "overrides": {
    "use-open-seadragon": {
      "react": "^17.0.2",
      "react-dom": "^17.0.2"
    }
},,
```

**Comment by stephenwf** [comment]
Thanks for getting to the bottom of that @Pramod-Butte ! Maybe we could change that in the package.json of this project to allow any react version.
